### ISSUE TITLE
Кастомизировать схему для сваггера

### ISSUE THREAD

**Issue by 8Vadim8** [staff-motivation/backend#37]
Тут два варианта: 
1. Создать отдельный файл schema.py где кастомизировать все эндпоинты(прописать все ошибки, для чего этот эндпоинт) 
вот пример реализации(https://github.com/Medical-Information/medical-information-backend/blob/develop/api/schema.py)
2. Либо у каждого эндпоинта в декораторе прописывать все это отдельно.

Выбор по вашему желанию

**Comment by robky** [comment]
Взял
